apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: taskmaster
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.taskmaster.svc.cluster.local:9090 # K8s internal service DNS
      access: proxy
      isDefault: true
      jsonData:
        manageAlerts: true # Optional: allow Grafana to manage Prometheus alerts
        # httpMethod: POST # If Prometheus expects POST for queries
      editable: true
