apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: taskmaster
  labels:
    app: grafana
spec:
  type: NodePort # Or LoadBalancer
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30003 # Example for Minikube access
  selector:
    app: grafana
