apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: taskmaster
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-collector.taskmaster.svc.cluster.local:8889"] # Scrape metrics from OTel collector

      - job_name: "kubernetes-pods" # Scrape pods directly if they expose /metrics and have annotations
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - taskmaster # Only scrape from our namespace
        relabel_configs:
          # Only scrape pods that have 'prometheus.io/scrape: true' annotation
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Use annotation for scrape path, default to /metrics
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use annotation for port
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          # Relabel pod name
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          # Relabel namespace
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          # Relabel service name from pod label 'app'
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: service
