apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: taskmaster
  labels:
    app: prometheus
spec:
  type: NodePort # Or LoadBalancer on cloud, ClusterIP if only Grafana needs access
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090 # Example for Minikube access
  selector:
    app: prometheus
